# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_PAT }}
    - name: Building with node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Remove unwanted files and change directory layout
      run: |
          mkdir todelete
          mv * todelete/
          mv todelete/dist .
          rm -rf todelete
          mv dist/* .
          rm -rf dist
    - name: Push to gh-pages
      run: |
          git config --global user.name 'William Watson'
          git config --global user.email 'williamdwatson@users.noreply.github.com'
          git fetch --unshallow origin gh-pages
          git checkout gh-pages
          git pull
          git add -A
          git commit -m "Automated build"
          git push
